spring:
  liquibase:
    contexts: dev
  devtools:
    restart:
      enabled: true
app:
  cookie:
    secure: false
    same-site: lax
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
