spring:
  liquibase:
    contexts: dev
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
cookie:
  secure: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
